### ISSUE TITLE
Parsing the BiorXiv data into the required JSON format

### ISSUE THREAD

**Issue by varshitakolipaka** [nbdt-journal/automatic-reviewer-assignment#3]
### Description
BiorXiv is a preprint server offers endpoints which can to derive information about research papers, more specific to the medical domain. 

### Output Format

The following is the required format for the data. Many entries do not have one or more attributes

```json
{
    "title": "...",
    "abstract": "...",
    "doi": "...",
    "authors": [
        {
            "name": "...",
            "number_on_paper": "...",
            "affiliations": ["...", "..."]
        },
        {
            "name": "...",
            "number_on_paper": "...",
            "affiliations": ["...", "..."]
        },
        "..."
    ],
    "source": "medline | bioarxiv | arxiv"
}
```
### Tasks

- [x] Design a relevant search query (to include computational neuroscience entries only)
- [x] Clean up the results to remove entries with "null" values for required fields, etc.
- [x] Write a script to retrieve data using the API, iterating through the pagination, in a JSON format
